[workspace]
channels = ["conda-forge"]
name = "WCSim"
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
root  = "==6.40.00"

[package]
name    = "WCSimRoot"
version = "1.12.34"

[package.build.source]
path = "."

[package.build.backend]
name     = "pixi-build-cmake"
channels = ["https://prefix.dev/conda-forge"]

[package.build.config]
extra-args = ["-DWCSim_WCSimRoot_only=ON"]

[package.build-dependencies]
cmake        = ">=3.5"
ninja        = "*"
cxx-compiler = "*"

[package.host-dependencies]
root = "==6.40.00"
